In [33]:
import numpy as np

In [34]:
#Question1
np.arange(2,50,3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [35]:
#Question2
list1 = list(map(int,input("\nEnter the numbers for List1 : ").strip().split()))[:5]
list2 = list(map(int,input("\nEnter the numbers for List2 : ").strip().split()))[:5]
array1 = np.array(list1)
array2 = np.array(list2)
np.concatenate((array1,array2),axis=0)



Enter the numbers for List1 : 1 7 6 3 8

Enter the numbers for List2 : 4 5 2 7 5


array([1, 7, 6, 3, 8, 4, 5, 2, 7, 5])

In [36]:
#Question3
print(array1.ndim)
print(array1.size)

1
5


In [37]:
#Question4
array_1D = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print('1D Numpy array:')
print(array_1D)
array_2D=np.reshape(array_1D,(-1,2))
print(array_2D)

1D Numpy array:
[0 1 2 3 4 5 6 7 8 9]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [38]:
#Question5
a = np.arange(4).reshape(2, 2)
print(a)
b = np.random.rand(2, 2)
print(b)
print(np.hstack((a,b)))
print(np.vstack((a,b)))

[[0 1]
 [2 3]]
[[0.87465177 0.77635882]
 [0.92984223 0.18903715]]
[[0.         1.         0.87465177 0.77635882]
 [2.         3.         0.92984223 0.18903715]]
[[0.         1.        ]
 [2.         3.        ]
 [0.87465177 0.77635882]
 [0.92984223 0.18903715]]


In [39]:
#Question6
import random
item_list = []
for i in range(0,30):
  n=random.randint(1,15)
  item_list.append(n)
print(item_list)

unique_items = set(item_list)
number_of_unique_values = len(unique_items)
print(unique_items)
print(number_of_unique_values)

[4, 1, 9, 3, 6, 13, 3, 15, 13, 13, 14, 4, 2, 11, 9, 10, 10, 2, 11, 8, 12, 14, 1, 6, 1, 7, 9, 5, 14, 14]
{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15}
15
